
POST_STATUS_HIDE = 0
POST_STATUS_SHOW = 9

POST_STATUS_CHOICES = (
	(POST_STATUS_HIDE, 'hidden'),
	(POST_STATUS_SHOW, 'public')
)

POST_CONTENT_TYPE_UNDEFINED = 0
POST_CONTENT_TYPE_HEADLINE = 1
POST_CONTENT_TYPE_TEXT = 2
POST_CONTENT_TYPE_IMAGE = 3
POST_CONTENT_TYPE_VIDEO = 4
POST_CONTENT_TYPE_CODE = 5

POST_CONTENT_TYPE_CHOICES = (
	(POST_CONTENT_TYPE_UNDEFINED, 'undefined'),
	(POST_CONTENT_TYPE_HEADLINE, 'headline'),
	(POST_CONTENT_TYPE_TEXT, 'text'),
	(POST_CONTENT_TYPE_IMAGE, 'image'),
	(POST_CONTENT_TYPE_VIDEO, 'video'),
	(POST_CONTENT_TYPE_CODE, 'code'),
)
