# Generated by Django 3.0.3 on 2020-03-15 02:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200305_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcontent',
            options={'ordering': ['order'], 'verbose_name': 'content', 'verbose_name_plural': 'contents'},
        ),
        migrations.AddField(
            model_name='postcontent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcontent',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'undefined'), (1, 'headline'), (2, 'text'), (3, 'image'), (4, 'video'), (5, 'code')], default=0),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'hidden'), (9, 'public')], default=0),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
